### ISSUE TITLE
Help In Creating Simple Java Program to Communicate Plivo Server

### ISSUE THREAD

**Issue by pankajmishra** [plivo/plivo-examples-java#2]
Sir I am new to Plivo and as Java Programmer I want to write a very basic Client which will communicate already installed Plivo Server.

What a initial Setup and needs to be done to create Such client which will
response an HTTP request coming to it and or hitting an http based request.

Pleas guide me to very basic communication

Like this and I want JavaApp:

```
      JavaApp <=======HTTP=======> Plivo Server<===============TCP/IP=============> Freeswitch
```

I want to know the classes, and libs to be implemented.

I have already got the jars but not the to use.
All though in PHP its looking very easy. Please help in Java That is requirement and I am assigned for that.

**Comment by huzaif-plivo** [comment]
@pankajmishra We request you to run through our [latest documentation](https://www.plivo.com/docs/sdk/server/java-sdk/#authentication) which contains a detailed start-up guide that will help you overcome the challenges you are facing. Feel free to reach out to the [support team](https://support.plivo.com/hc/en-us) for any queries.
