### ISSUE TITLE
answer_url called twice, one for GET and once for POST

### ISSUE THREAD

**Issue by skairamk** [plivo/plivo-examples-java#5]
Hi,

i used the basic example https://github.com/plivo/plivo-examples-java/blob/master/voice/call_api/make_calls.java. I am able to receive the call, but i am seeing the call twice in the plivo logs. 
As specified in the answer_url and answer_method, its invoking for GET, but also again, once the call is hang up, its again calling the same url using POST. why it is calling again using POST method?

Please the below logs:

1st time request:
Message : http request
URL : https://dry-fortress-4047.herokuapp.com/speak
HTTP Type : request
Method: GET
Headers : {
      X-Plivo-Signature : joochajPFUHJydQnwex+VYK6jms=
    }
Params : {
      Direction : outbound
      From : 18052209193
      ALegUUID : 5cf2caa0-f651-488f-a591-bca97d6e08b9
      BillRate : 0.012
      To : 18479874489
      CallUUID : 5cf2caa0-f651-488f-a591-bca97d6e08b9
      ALegRequestUUID : 1a640ad4-a238-436d-844e-50679917dec3
      RequestUUID : 1a640ad4-a238-436d-844e-50679917dec3
      CallStatus : in-progress
      Event : StartApp
    }

1st time response:
Message : http response success
Status : 200
URL : https://dry-fortress-4047.herokuapp.com/speak
HTTP Type : response
Method: GET
Headers : {
      date : Thu, 22 Sep 2016 03:11:00 GMT
      connection : close
      via : 1.1 vegur
      content-type : text/xml
      server : Jetty(7.2.2.v20101205)
    }
Content : <Response><Speak>Hello, Welcome to Plivo</Speak></Response>

2nd time request: using POST this time, with event Hangup:

Message : http request
URL : https://dry-fortress-4047.herokuapp.com/speak
HTTP Type : request
Method: POST
Headers : {
      X-Plivo-Signature : atDJTw636XnimxKmRQl96jP2Zi0=
    }
Params : {
      TotalCost : 0.01200
      Direction : outbound
      HangupCause : NORMAL_CLEARING
      From : 18052209193
      Duration : 3
      ALegUUID : 5cf2caa0-f651-488f-a591-bca97d6e08b9
      BillDuration : 60
      BillRate : 0.012
      To : 18479874489
      AnswerTime : 2016-09-21 22:11:00
      StartTime : 2016-09-21 22:10:51
      CallUUID : 5cf2caa0-f651-488f-a591-bca97d6e08b9
      ALegRequestUUID : 1a640ad4-a238-436d-844e-50679917dec3
      RequestUUID : 1a640ad4-a238-436d-844e-50679917dec3
      EndTime : 2016-09-21 22:11:03
      CallStatus : completed
      Event : Hangup
    }

2nd time response: error response:

Message : http response failure
Status : 405
URL : https://dry-fortress-4047.herokuapp.com/speak
HTTP Type : response
Method: POST
Headers : {
      content-length : 1344
      via : 1.1 vegur
      server : Jetty(7.2.2.v20101205)
      connection : close
      cache-control : must-revalidate,no-cache,no-store
      date : Thu, 22 Sep 2016 03:11:03 GMT
      content-type : text/html;charset=ISO-8859-1
    }
Content : <html> <head> <meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/> <title>Error 405 HTTP method POST is not supported by this URL</title> </head> <body> <h2>HTTP ERROR: 405</h2> <p>Problem accessing /speak. Reason: <pre> HTTP method POST is not supported by this URL</pre></p> <hr /><i><small>Powered by Jetty://</small></i> ...(Trucated)

Any help regarding this is much appreciated.

**Comment by Ramya-Raghu** [comment]
@skairamk Answer URL is requested when the call is answered by the user. Once the call ends, Plivo makes a request to the Hangup URL with the details of the call. When a Hangup URL is not configured, it falls back to the Answer URL, which is why you see the second request using POST to your Answer URL. You could configure a Hangup URL while making the outbound API call request.

**Comment by skairamk** [comment]
thank you very much @Ramya-Raghu . Its makes sense now.
