### ISSUE TITLE
Voice callWhisper Example Flip-Flop

### ISSUE THREAD

**Issue by KarmicJohn** [plivo/plivo-examples-java#6]
I believe the ConfirmKey and ConfirmSound are flip-flopped here:

```java
dial.setConfirmKey("https://dry-fortress-4047.herokuapp.com/confirm_sound");
        dial.setConfirmSound("5");
```

**Comment by huzaif-plivo** [comment]
@KarmicJohn Thank you for highlighting the concern, we have now taken care of the issue by updating all our code snippets to the latest version
